CREATE DATABASE IF NOT EXISTS helxdb CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
USE helxdb;

CREATE TABLE IF NOT EXISTS users (
    id INT PRIMARY KEY AUTO_INCREMENT,
    username VARCHAR(100) UNIQUE NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    phone VARCHAR(20) UNIQUE,
    full_name VARCHAR(255),
    profile_image VARCHAR(255),
    user_type ENUM('job_seeker', 'employer', 'admin') NOT NULL,
    status ENUM('active', 'inactive', 'suspended', 'pending_verification') DEFAULT 'pending_verification',
    email_verified BOOLEAN DEFAULT FALSE,
    phone_verified BOOLEAN DEFAULT FALSE,
    verification_token VARCHAR(255),
    reset_token VARCHAR(255),
    reset_token_expires DATETIME,
    last_login DATETIME,
    two_factor_enabled BOOLEAN DEFAULT FALSE,
    two_factor_code VARCHAR(6),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_email (email),
    INDEX idx_user_type (user_type),
    INDEX idx_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS job_seekers (
    id INT PRIMARY KEY AUTO_INCREMENT,
    user_id INT NOT NULL UNIQUE,
    headline VARCHAR(255),
    bio TEXT,
    current_city VARCHAR(100),
    target_cities TEXT,
    job_title VARCHAR(100),
    experience_years INT,
    education_level ENUM('high_school', 'diploma', 'bachelor', 'master', 'phd'),
    employment_type SET('full_time', 'part_time', 'freelance', 'contract', 'internship'),
    salary_expectation_min INT,
    salary_expectation_max INT,
    currency VARCHAR(3) DEFAULT 'YER',
    availability_status ENUM('actively_looking', 'open_to_opportunities', 'not_looking') DEFAULT 'actively_looking',
    resume_file VARCHAR(255),
    resume_content LONGTEXT,
    cv_summary TEXT,
    linkedin_url VARCHAR(255),
    github_url VARCHAR(255),
    portfolio_url VARCHAR(255),
    completed_courses INT DEFAULT 0,
    cv_score INT DEFAULT 0,
    profile_completeness INT DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    INDEX idx_experience (experience_years),
    INDEX idx_availability (availability_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS employers (
    id INT PRIMARY KEY AUTO_INCREMENT,
    user_id INT NOT NULL UNIQUE,
    company_name VARCHAR(255) NOT NULL,
    company_logo VARCHAR(255),
    company_description TEXT,
    industry VARCHAR(100),
    company_size ENUM('startup', 'small', 'medium', 'large', 'enterprise'),
    founded_year YEAR,
    headquarters_city VARCHAR(100),
    company_website VARCHAR(255),
    company_phone VARCHAR(20),
    company_email VARCHAR(100),
    verification_status ENUM('pending', 'verified', 'rejected') DEFAULT 'pending',
    verification_document VARCHAR(255),
    subscription_status ENUM('free', 'basic', 'premium', 'enterprise') DEFAULT 'free',
    subscription_expires DATETIME,
    job_posts_limit INT DEFAULT 5,
    active_jobs INT DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    INDEX idx_verification (verification_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS notification_preferences (
    id INT PRIMARY KEY AUTO_INCREMENT,
    user_id INT NOT NULL UNIQUE,
    email_notifications BOOLEAN DEFAULT TRUE,
    sms_notifications BOOLEAN DEFAULT TRUE,
    push_notifications BOOLEAN DEFAULT TRUE,
    in_app_notifications BOOLEAN DEFAULT TRUE,
    new_job_match_email BOOLEAN DEFAULT TRUE,
    new_job_match_sms BOOLEAN DEFAULT TRUE,
    application_status_email BOOLEAN DEFAULT TRUE,
    application_status_sms BOOLEAN DEFAULT TRUE,
    profile_viewed_email BOOLEAN DEFAULT TRUE,
    interview_request_email BOOLEAN DEFAULT TRUE,
    interview_request_sms BOOLEAN DEFAULT TRUE,
    daily_digest BOOLEAN DEFAULT FALSE,
    weekly_digest BOOLEAN DEFAULT FALSE,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
